# Program to extract Kepler IDs from a .tsv generated by Vizier

# Carly Hessler
# 10/14/2014

import csv
import numpy as np

keplerList = []

def reader(fileName):
    with open(fileName, 'rU') as csvfile:
        starReader = csv.reader(csvfile, delimiter=';')
        starReader.next()
        i = 0   # necessary as I am a bad programmer
        for row in starReader:
            if row and i > 34:    # this isn't good coding, I'm aware, but it works
                print row
                keplerList.append(row)
            i += 1
        # note that at the end, i will be OVER NINE THOUSAAAAND. VizieR spits out blank rows which I removed

def writeToFile(fileName):
    writer = csv.writer(open(fileName, "wb"))
    for row in keplerList:
        writer.writerow(row)

np.set_printoptions(threshold='nan')
reader('C:/Users/Carly/PycharmProjects/KeplerIDExtractor/asu.tsv')
print(len(keplerList))
print
# not entirely sure how they got in but there were empty lines
'''del(starList[2460])
del(starList[2836])
del(starList[3070])
del(starList[3080])
del(starList[3684])
del(starList[3929])'''
#TODO: Re-code such that the empty lines are thrown out

writeToFile('theIDs.csv')